### ISSUE TITLE
Semver range parser error:

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/libpkgx#42]
The range `>=1<1.0.19` is an invalid constraint, but `>=1.0<1.0.19` behaves correctly. Seems wrong.

`  libsodium.org: '>=1<1.0.19'`
```shell
error: Uncaught Error: invalid constraint for libsodium.org: undefined
    throw new TeaError("invalid constraint for " + project + ": " + constraint)
          ^
    at validatePackageRequirement (https://deno.land/x/libtea@v0.11.2/src/utils/hacks.ts:31:11)
    at https://deno.land/x/libtea@v0.11.2/src/hooks/usePantry.ts:266:7
    at Array.compact (https://deno.land/x/libtea@v0.11.2/src/utils/misc.ts:55:24)
    at parse_pkgs_node (https://deno.land/x/libtea@v0.11.2/src/hooks/usePantry.ts:265:6)
    at Object.getDeps (file:///Users/jacob/.tea/tea.xyz/brewkit/v0.45.5/lib/usePantry.ts:31:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///Users/jacob/.tea/tea.xyz/brewkit/v0.45.5/libexec/sort.ts:24:16
    at async ascend (https://deno.land/x/libtea@v0.11.2/src/plumbing/hydrate.ts:62:25)
    at async go (https://deno.land/x/libtea@v0.11.2/src/plumbing/hydrate.ts:93:5)
    at async hydrate (https://deno.land/x/libtea@v0.11.2/src/plumbing/hydrate.ts:102:7)
```

`  libsodium.org: '>=1.0<1.0.19'`
```shell
  
  building php.net
...
```

**Comment by jhheider** [comment]
Interestingly, >=1.0<1.0.19 gets further reduced in the stage step: https://github.com/teaxyz/pantry/actions/runs/6200325679/job/16834801653
