### ISSUE TITLE
[low] deno std library throwing a warning with newer versions of deno

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/libpkgx#77]
```shell
⚠️  Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.
import data from "./_data.json" assert { type: "json" };
  at https://deno.land/std@0.196.0/console/unicode_width.ts:4:1
```

per deno.land:

`The Standard Library has been moved to [JSR](https://jsr.io/@std). See [the blog post](https://deno.com/blog/std-on-jsr) for details.`

**Comment by mxcl** [comment]
is this shown at runtime or compile time? Specifically when is this warning shown?

**Comment by jhheider** [comment]
runtime. see: https://github.com/pkgxdev/pantry/actions/runs/11036300859/job/30654439828

```shell
Run pkgxdev/brewkit/audit@v1
Run if ! pkgx --sync; then

Run echo "::group::fetch deno deps"
fetch deno deps
Run ${GITHUB_ACTION_PATH}/audit.ts '{"project":"cnquery.io","version":{"value":"11.23.1","raw":"11.23.1","tag":"v11.23.1"}}'
⚠️  Import assertions are deprecated. Use `with` keyword, instead of 'assert' keyword.

import data from "./_data.json" assert { type: "json" };

  at https://deno.land/std@0.196.0/console/unicode_width.ts:4:1
```

**Comment by mxcl** [comment]
We now use the jsr
